# ----------------------------------
# config for the website plugin
# ---------------------------------

# all URIs given here are internal to the website plugin

config_sharedDirs:
  - dirConfig_path: demo/content
    dirConfig_uriPrefix: / # directory name in URI
  - dirConfig_path: demo/css
    dirConfig_uriPrefix: /css # directory name in URI
  - dirConfig_path: demo/data
    dirConfig_uriPrefix: /data # directory name in URI
config_userCSS: ["content/css/style.css"] # uri of the user css
config_addToHeader: |
  <!-- user defined additions to "/html/head" -->
config_content: "demo/config/content.yaml" # file defining site hierarchy
config_defaultRoute: "0_infos" # empty url ("/") is mapped to this uri
