##
#
#

config_sharedDirs:
  - dirConfig_path: demo/content
    dirConfig_uriPrefix: / # directory name in URI
  - dirConfig_path: demo/css
    dirConfig_uriPrefix: /css # directory name in URI
  - dirConfig_path: demo/data
    dirConfig_uriPrefix: /data # directory name in URI
config_userCSS: "content/css/style.css" # uri of the user css
config_content: "demo/content.yaml" # file defining site hierarchy
